// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3DTp72LxtzGhO5HsZXQ8XUZ3Le8OIeU',
    appId: '1:563664891573:web:94ca453cefcb03a9e2d8fc',
    messagingSenderId: '563664891573',
    projectId: 'quickdrop-38749',
    authDomain: 'quickdrop-38749.firebaseapp.com',
    storageBucket: 'quickdrop-38749.firebasestorage.app',
    measurementId: 'G-LMJ2SHJ18S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfsbatOfyey52SgogqVwYAJ5Gezkc6s4Y',
    appId: '1:563664891573:android:eb43c5f4ac2dd4dae2d8fc',
    messagingSenderId: '563664891573',
    projectId: 'quickdrop-38749',
    storageBucket: 'quickdrop-38749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aJ05UZkf-bdEgbR_yvbJBaOP-8JbhSo',
    appId: '1:563664891573:ios:400a05112d7b3c25e2d8fc',
    messagingSenderId: '563664891573',
    projectId: 'quickdrop-38749',
    storageBucket: 'quickdrop-38749.firebasestorage.app',
    androidClientId: '563664891573-ia23apcpijr74vf0cbhagj13u0vrmegg.apps.googleusercontent.com',
    iosClientId: '563664891573-hhb7rfrd29o2himj2bpesd2nhohn6lav.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickdropApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2aJ05UZkf-bdEgbR_yvbJBaOP-8JbhSo',
    appId: '1:563664891573:ios:400a05112d7b3c25e2d8fc',
    messagingSenderId: '563664891573',
    projectId: 'quickdrop-38749',
    storageBucket: 'quickdrop-38749.firebasestorage.app',
    androidClientId: '563664891573-ia23apcpijr74vf0cbhagj13u0vrmegg.apps.googleusercontent.com',
    iosClientId: '563664891573-hhb7rfrd29o2himj2bpesd2nhohn6lav.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickdropApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk3DTp72LxtzGhO5HsZXQ8XUZ3Le8OIeU',
    appId: '1:563664891573:web:45b452c6df0c1a49e2d8fc',
    messagingSenderId: '563664891573',
    projectId: 'quickdrop-38749',
    authDomain: 'quickdrop-38749.firebaseapp.com',
    storageBucket: 'quickdrop-38749.firebasestorage.app',
    measurementId: 'G-4YFLKHFEDC',
  );
}
